name: add_joke

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pyjokes
        run: |
          python -m pip install --upgrade pip
          pip install pyjokes

      - name: Print a joke
        run: |
          python -c "import pyjokes; print(pyjokes.get_joke())"
