name: add_joke

# Add permissions for contents: write
permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pyjokes
        run: |
          python -m pip install --upgrade pip
          pip install pyjokes

      - name: Add joke to README
        run: |
          joke=$(python -c "import pyjokes; print(pyjokes.get_joke())")
          sed -i '/<!-- JOKE_PLACEHOLDER -->/c\## Joke of the day\n\n$joke\n' README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Add joke of the day"

      - name: Push changes
        run: |
          git push
